### ISSUE TITLE
Warning/error spam 1.21.4

### ISSUE THREAD

**Issue by ChrisTVH** [CoolLord22/SkyParticles#2]
## Steps to reproduce:
- Create a WorldGuard region and assign it as a particle zone with `/sp worldguard`.

## Config
```yaml
particles:
  spawn@Aurora:
    particle: SCULK_SOUL
    distance: 4.0
    count: 30
    speed: 0.1
    world: spawn
    pos1:
      x: 12
      y: -42
      z: -7
    pos2:
      x: 23
      y: -38
      z: 4
    enabled: true
```
## Server log
https://mclo.gs/VjfDZ3l
## Technical details
- WorldGuard version 7.0.13+82fdc65
- UniverseSpigot version 1.21.4-ver/1.21.4-stable (Pufferfish fork)
- SkyParticles version 3.0
